#!/bin/bash

echo "🔧 Google Places API Setup Guide"
echo "=================================="
echo ""
echo "Your API Key: AIzaSyBRaCjDtoLx_DnzjCQ4RyImwL_KwpVY8yo"
echo "Project ID: 302910440522"
echo ""
echo "⚠️  Currently Missing APIs:"
echo "   ❌ Places API (New)"
echo "   ❌ Places API (Legacy) - might also be disabled"
echo ""
echo "📋 Step-by-Step Instructions:"
echo "=============================="
echo ""
echo "Option 1: Enable Places API (New) - RECOMMENDED"
echo "-----------------------------------------------"
echo "1. Open this link:"
echo "   👉 https://console.developers.google.com/apis/api/places.googleapis.com/overview?project=302910440522"
echo ""
echo "2. Click the 'ENABLE' button"
echo "3. Wait ~2 minutes for propagation"
echo "4. Test again"
echo ""
echo "Option 2: Enable Places API (Legacy)"
echo "------------------------------------"
echo "1. Open this link:"
echo "   👉 https://console.developers.google.com/apis/library/places-backend.googleapis.com?project=302910440522"
echo ""
echo "2. Click 'ENABLE'"
echo "3. Wait ~2 minutes"
echo "4. Test again"
echo ""
echo "💡 Quick Test Command:"
echo "======================"
echo ""
echo "# Test after enabling:"
echo 'curl -s "https://places.googleapis.com/v1/places:searchText" \'
echo '  -H "Content-Type: application/json" \'
echo '  -H "X-Goog-Api-Key: AIzaSyBRaCjDtoLx_DnzjCQ4RyImwL_KwpVY8yo" \'
echo '  -H "X-Goog-FieldMask: places.displayName,places.photos" \'
echo '  -d '"'"'{"textQuery": "Fukuoka Tower"}'"'"
echo ""
echo "✅ If successful, you'll see place data with photos"
echo "❌ If still failing, check billing is enabled in Google Cloud Console"
echo ""
echo "📊 Cost Monitoring:"
echo "==================="
echo "- First 100,000 photo requests/month: FREE"
echo "- After that: \$7 per 1,000 requests"
echo ""
echo "Set budget alerts at:"
echo "👉 https://console.cloud.google.com/billing/linkedaccount?project=302910440522"
echo ""
